### ISSUE TITLE
Fix MSVC build

### ISSUE THREAD

**Issue by yuanming-hu** [yuanming-hu/taichi#166]
It seems to work with MSVC `14.14.26428` but not `14.15.26726`...

**Comment by mirlip** [comment]
I don't know if it's linked, but the error on latest VS version is :
`c:\program files (x86)\microsoft visual studio\2017\vc\tools\msvc\14.15.26726\include\type_traits(1271): error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior. (compiling source file c:\taichi\include\taichi\visualization\particle_visualization.cpp) [c:\taichi\build\taichi_core.vcxproj]`

so maybe adding one of those define will solve the problem?

**Comment by yuanming-hu** [comment]
That could be the case - on my Windows machine I cannot reproduce the compilation error. Is there any chance you can give it a shot by defining `_ENABLE_EXTENDED_ALIGNED_STORAGE`? Thanks!

**Comment by mirlip** [comment]
at least it now compiles with the defines

**Comment by mirlip** [comment]
This is a diff to fix:
```
diff --git a/include/taichi/math/levelset.cpp b/include/taichi/math/levelset.cpp
index a83fe09..d4679c9 100644
--- a/include/taichi/math/levelset.cpp
+++ b/include/taichi/math/levelset.cpp
@@ -2,7 +2,7 @@
     Copyright (c) The Taichi Authors (2016- ). All Rights Reserved.
     The use of this software is governed by the LICENSE file.
 *******************************************************************************/
-
+#define _ENABLE_EXTENDED_ALIGNED_STORAGE
 #include "levelset.h"
 
 TC_NAMESPACE_BEGIN
diff --git a/include/taichi/visualization/particle_visualization.cpp b/include/taichi/visualization/particle_visualization.cpp
index 1f94177..ad4469d 100644
--- a/include/taichi/visualization/particle_visualization.cpp
+++ b/include/taichi/visualization/particle_visualization.cpp
@@ -2,7 +2,7 @@
     Copyright (c) The Taichi Authors (2016- ). All Rights Reserved.
     The use of this software is governed by the LICENSE file.
 *******************************************************************************/
-
+#define _ENABLE_EXTENDED_ALIGNED_STORAGE
 #include "particle_visualization.h"
 #include <taichi/math/array_3d.h>
 
@@ -135,5 +135,5 @@ std::shared_ptr<Texture> rasterize_render_particles(
   auto tex = create_instance<Texture>("array3d", cfg);
   return tex;
 }
-
+#undef _ENABLE_EXTENDED_ALIGNED_STORAGE
 TC_NAMESPACE_END
diff --git a/src/camera/pinhole.cpp b/src/camera/pinhole.cpp
index a73d136..222dd5f 100644
--- a/src/camera/pinhole.cpp
+++ b/src/camera/pinhole.cpp
@@ -2,7 +2,7 @@
     Copyright (c) The Taichi Authors (2016- ). All Rights Reserved.
     The use of this software is governed by the LICENSE file.
 *******************************************************************************/
-
+#define _ENABLE_EXTENDED_ALIGNED_STORAGE
 #include <taichi/visual/camera.h>
 
 TC_NAMESPACE_BEGIN
diff --git a/src/camera/thinlens.cpp b/src/camera/thinlens.cpp
index e4e9670..89ff43d 100644
--- a/src/camera/thinlens.cpp
+++ b/src/camera/thinlens.cpp
@@ -2,7 +2,7 @@
     Copyright (c) The Taichi Authors (2016- ). All Rights Reserved.
     The use of this software is governed by the LICENSE file.
 *******************************************************************************/
-
+#define _ENABLE_EXTENDED_ALIGNED_STORAGE
 #include <taichi/visual/camera.h>
 
 TC_NAMESPACE_BEGIN
diff --git a/src/environment_map/envmap.cpp b/src/environment_map/envmap.cpp
index 94f53ad..440147c 100644
--- a/src/environment_map/envmap.cpp
+++ b/src/environment_map/envmap.cpp
@@ -2,7 +2,7 @@
     Copyright (c) The Taichi Authors (2016- ). All Rights Reserved.
     The use of this software is governed by the LICENSE file.
 *******************************************************************************/
-
+#define _ENABLE_EXTENDED_ALIGNED_STORAGE
 #include <taichi/visual/envmap.h>
 #include <taichi/visual/texture.h>
 #include <taichi/common/asset_manager.h>
diff --git a/src/python/export_visual.cpp b/src/python/export_visual.cpp
index 255a3ad..4c2727a 100644
--- a/src/python/export_visual.cpp
+++ b/src/python/export_visual.cpp
@@ -2,7 +2,7 @@
     Copyright (c) The Taichi Authors (2016- ). All Rights Reserved.
     The use of this software is governed by the LICENSE file.
 *******************************************************************************/
-
+#define _ENABLE_EXTENDED_ALIGNED_STORAGE
 #include <taichi/python/export.h>
 
 #include <taichi/math/sdf.h>
diff --git a/src/renderer/pt.cpp b/src/renderer/pt.cpp
index 953a800..c0efffe 100644
--- a/src/renderer/pt.cpp
+++ b/src/renderer/pt.cpp
@@ -2,7 +2,7 @@
     Copyright (c) The Taichi Authors (2016- ). All Rights Reserved.
     The use of this software is governed by the LICENSE file.
 *******************************************************************************/
-
+#define _ENABLE_EXTENDED_ALIGNED_STORAGE
 #include <taichi/system/threading.h>
 #include <taichi/visual/renderer.h>
 #include <taichi/visual/sampler.h>
diff --git a/src/simulation/fluid_3d.cpp b/src/simulation/fluid_3d.cpp
index f8c4792..1310d9f 100644
--- a/src/simulation/fluid_3d.cpp
+++ b/src/simulation/fluid_3d.cpp
@@ -2,7 +2,7 @@
     Copyright (c) The Taichi Authors (2016- ). All Rights Reserved.
     The use of this software is governed by the LICENSE file.
 *******************************************************************************/
-
+#define _ENABLE_EXTENDED_ALIGNED_STORAGE
 #include "fluid_3d.h"
 #include <taichi/common/util.h>
 #include <taichi/math/array.h>
diff --git a/src/simulation/nbody.cpp b/src/simulation/nbody.cpp
index 5d8ea36..b19e02a 100644
--- a/src/simulation/nbody.cpp
+++ b/src/simulation/nbody.cpp
@@ -2,7 +2,7 @@
     Copyright (c) The Taichi Authors (2016- ). All Rights Reserved.
     The use of this software is governed by the LICENSE file.
 *******************************************************************************/
-
+#define _ENABLE_EXTENDED_ALIGNED_STORAGE
 #include <taichi/dynamics/simulation.h>
 #include <taichi/visualization/particle_visualization.h>
 #include <taichi/visual/texture.h>
diff --git a/src/texture/gradient_texture.cpp b/src/texture/gradient_texture.cpp
index 9951fb0..9299047 100644
--- a/src/texture/gradient_texture.cpp
+++ b/src/texture/gradient_texture.cpp
@@ -2,7 +2,7 @@
     Copyright (c) The Taichi Authors (2016- ). All Rights Reserved.
     The use of this software is governed by the LICENSE file.
 *******************************************************************************/
-
+#define _ENABLE_EXTENDED_ALIGNED_STORAGE
 #include <taichi/visual/texture.h>
 
 TC_NAMESPACE_BEGIN
diff --git a/src/texture/sky_texture.cpp b/src/texture/sky_texture.cpp
index d1e0b31..26c7abc 100644
--- a/src/texture/sky_texture.cpp
+++ b/src/texture/sky_texture.cpp
@@ -2,7 +2,7 @@
     Copyright (c) The Taichi Authors (2016- ). All Rights Reserved.
     The use of this software is governed by the LICENSE file.
 *******************************************************************************/
-
+#define _ENABLE_EXTENDED_ALIGNED_STORAGE
 #include <taichi/visual/texture.h>
 
 TC_NAMESPACE_BEGIN
diff --git a/src/texture/sources.cpp b/src/texture/sources.cpp
index 3c60ebb..fc9dc6d 100644
--- a/src/texture/sources.cpp
+++ b/src/texture/sources.cpp
@@ -2,7 +2,7 @@
     Copyright (c) The Taichi Authors (2016- ). All Rights Reserved.
     The use of this software is governed by the LICENSE file.
 *******************************************************************************/
-
+#define _ENABLE_EXTENDED_ALIGNED_STORAGE
 #include <taichi/visual/texture.h>
 #include <taichi/visual/scene_geometry.h>
 #include <taichi/visualization/image_buffer.h>
diff --git a/src/texture/texture_op.cpp b/src/texture/texture_op.cpp
index 13cfb79..535a208 100644
--- a/src/texture/texture_op.cpp
+++ b/src/texture/texture_op.cpp
@@ -2,7 +2,7 @@
     Copyright (c) The Taichi Authors (2016- ). All Rights Reserved.
     The use of this software is governed by the LICENSE file.
 *******************************************************************************/
-
+#define _ENABLE_EXTENDED_ALIGNED_STORAGE
 #include <taichi/visual/texture.h>
 #include <taichi/common/asset_manager.h>
 
diff --git a/src/volume_material/volume_material.cpp b/src/volume_material/volume_material.cpp
index 07de9c4..56de417 100644
--- a/src/volume_material/volume_material.cpp
+++ b/src/volume_material/volume_material.cpp
@@ -2,7 +2,7 @@
     Copyright (c) The Taichi Authors (2016- ). All Rights Reserved.
     The use of this software is governed by the LICENSE file.
 *******************************************************************************/
-
+#define _ENABLE_EXTENDED_ALIGNED_STORAGE
 #include <queue>
 #include <taichi/visual/volume_material.h>
 #include <taichi/visual/texture.h>

```

**Comment by yuanming-hu** [comment]
I simply added `-D_ENABLE_EXTENDED_ALIGNED_STORAGE` to the compiler flags and it seems to work now. Thank you so much!
